# Generated by Django 5.0.2 on 2024-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overall_square', models.IntegerField()),
                ('living_square', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('view_from_windows', models.CharField(blank=True, choices=[('courtyard', 'внутренний двор'), ('street_outside', 'внешняя улица')], default='courtyard', max_length=120)),
                ('lavatory', models.IntegerField()),
                ('level', models.IntegerField()),
                ('elevator', models.CharField(max_length=120)),
                ('year_of_sale', models.IntegerField()),
                ('parking', models.CharField(choices=[('on_ground', 'наземный'), ('underground', 'подземный')], default='on_ground', max_length=50)),
                ('is_complete', models.BooleanField(default=True)),
                ('is_kitchen', models.BooleanField()),
            ],
        ),
    ]
