# Generated by Django 5.0.2 on 2024-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('overall_square', models.PositiveIntegerField()),
                ('living_square', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('view_from_windows', models.CharField(blank=True, choices=[('courtyard', 'внутренний двор'), ('street_outside', 'внешняя улица')], default='courtyard', max_length=120)),
                ('lavatory', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('elevator', models.PositiveIntegerField()),
                ('year_of_sale', models.PositiveIntegerField()),
                ('parking', models.CharField(choices=[('on_ground', 'наземный'), ('underground', 'подземный')], default='on_ground', max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField()),
                ('floor', models.ManyToManyField(to='realty.floor')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
