# Generated by Django 5.0.2 on 2024-04-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='living_space',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='square',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='status',
        ),
        migrations.AddField(
            model_name='flat',
            name='elevator',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='has_kitchen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='lavatory',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='level',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='living_square',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='name',
            field=models.CharField(default=False, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='overall_square',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='parking',
            field=models.CharField(choices=[('on_ground', 'наземный'), ('underground', 'подземный')], default='on_ground', max_length=50),
        ),
        migrations.AddField(
            model_name='flat',
            name='view_from_windows',
            field=models.CharField(blank=True, choices=[('courtyard', 'внутренний двор'), ('street_outside', 'внешняя улица')], default='courtyard', max_length=120),
        ),
        migrations.AddField(
            model_name='flat',
            name='year_of_sale',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
