# Generated by Django 5.0.2 on 2024-03-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_alter_flat_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveSmallIntegerField(verbose_name='Номер этажа')),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.floor', verbose_name='Этаж'),
        ),
    ]
