# Generated by Django 5.0.2 on 2024-03-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_floor_alter_flat_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Luxe', 'Люкс')], db_index=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.flatcategory', verbose_name='Класс квартиры'),
        ),
    ]
