# Generated by Django 5.0.2 on 2024-03-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_floor_alter_flat_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Эконом'), (2, 'Комфорт'), (3, 'Люкс')], db_index=True, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='realty.flatclass', verbose_name='Класс квартиры'),
        ),
    ]
