# Generated by Django 5.0.2 on 2024-03-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_flatcategory_flat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_construction', models.DateField()),
                ('date_of_delivery', models.DateField()),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер дома')),
                ('status', models.CharField(choices=[('Under construction', 'Строится'), ('Passed', 'Сдан')], default='Under construction', max_length=25, verbose_name='Статус')),
                ('type', models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Monolithic', 'Монолитный'), ('Panel', 'Панельный')], max_length=10, null=True, verbose_name='Тип дома')),
                ('has_parking', models.BooleanField(default=True, verbose_name='Паркинг')),
                ('elevators', models.IntegerField(choices=[('Zero', 0), ('One', 1), ('Two', 2), ('Three', 3)], default='Two', verbose_name='Лифты')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building'),
        ),
    ]
