# Generated by Django 5.0.2 on 2024-03-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_flatcategory_flat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_construction', models.DateField()),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер дома')),
                ('status', models.CharField(blank=True, choices=[('Under construction', 'Строится'), ('Passed', 'Сдан')], max_length=18, null=True, verbose_name='Статус')),
                ('type', models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Monolithic', 'Монолитный'), ('Panel', 'Панельный')], max_length=10, null=True, verbose_name='Тип дома')),
                ('parking', models.CharField(blank=True, choices=[('Present', 'Присутствует'), ('Missing', 'Отсутствует')], max_length=7, null=True, verbose_name='Паркинг')),
                ('elevators', models.CharField(blank=True, choices=[('Missing', 'Отсутсвуют'), ('One', 'Один'), ('Two', 'Два'), ('Three', 'Три')], max_length=7, null=True, verbose_name='Лифты')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building'),
        ),
    ]
