# Generated by Django 5.0.2 on 2024-03-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_building_flat_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер проекта')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.project'),
        ),
    ]
