# Generated by Django 5.0.2 on 2024-04-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_project_alter_building_name_building_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
